#! /usr/bin/env ruby
# Alphabetizes the terms in _data/terms.yml

require 'psych'

data_dir = File.expand_path( "../_data", File.dirname(__FILE__))
data_file = File.expand_path "terms.yml", data_dir

terms = Psych.load_file data_file
terms = terms.sort_by { |k,v| k.downcase }.to_h

output = Psych.dump(terms, :line_width => -1)
output.gsub! /\n/, "\n\n"
output.gsub! /\n\Z/m, ""
output << "\n"

File.open( data_file, 'w' ) { |f| f.write output }
